### PR TITLE
remove requirements from aria label prop type

### PR DESCRIPTION
**Pull request by andynhi**
remove required prop type for ariaLabel or update documentation to reflect its requirement within the component

http://react.carbondesignsystem.com/?selectedKind=Dropdown&selectedStory=with%20default%20text&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Closes carbon-design-system/carbon-components-react#

{{short description}}

#### Changelog

**New**

* {{new thing}}

**Changed**

* {{change thing}}

**Removed**

* {{removed thing}}

### CODE REVIEW

**Comment by asudoh** [comment]
Hi @andynhi thank you for contributing - IIUC the `isRequired` is intentional for a11y sake, but let’s see what others think. CC @tw15egan @marijohannessen

**Comment by alisonjoseph** [comment]
Agree with @asudoh that we should keep this prop for a11y purposes. What was the reasoning behind wanting to remove the required @andynhi ?

**Comment by tw15egan** [comment]
Agreed, this is required for `a11y` sake. If you want, you can change this PR to update the documentation, but the prop should stay `required`

**Comment by marijohannessen** [comment]
@andynhi please let us know if you want to change this PR to update the documentation or not by next Friday, if we don't hear from you by then we will close this PR due to inactivity.

**Comment by andynhi** [comment]
sorry for late response, yeah you can close the tickets as long as the document reflects the requirement of the prop, thanks

**Comment by andynhi** [comment]
@marijohannessen

sorry for late response, closing the ticket - ill send a PR to update docs

**Comment by andynhi** [comment]
@marijohannessen  its possible that story book is having trouble reading static propTypes within the es6 class format - i noticed that all the pure components with propTypes work with storybook

**Pull request closed without merging**
