### PR TITLE
[WIP] fix(multiselect): ensure there are not duplicate id's

### PR DESCRIPTION
**Pull request by tw15egan**
Closes carbon-design-system/carbon-components-react#615

Fixes a11y issues with `MultiSelect`

#### Changelog

**Changed**

* Added `-input` to the end of the checkbox `id` to ensure no duplicates.
* Added `evt.stopPropagation()` to inner `Checkbox` to ensure selection works properly

### CODE REVIEW

**Comment by marijohannessen** [comment]
multiselect

The checkboxes are acting a bit weird when I select them - not sure if that's because of this PR or not?

**Comment by marijohannessen** [comment]
Hey @joshblack , the weird focus issue happens when the `-input` part is applied to the checkbox id. When I move it back to what it was, it goes away but then the a11y problem still exists. Do you know what might be causing this?

**Comment by joshblack** [comment]
@marijohannessen honestly not sure 😞 seems like the selection is causing the focus state to be triggered for the underlying node, despite the fact that it is moving to the top of the list. First guess would be some index-related bug with how downshift places items in its class instance.

**Comment by shinytoyrobots** [comment]
Closing as unmerged.

**Pull request closed without merging**
