### PR TITLE
fix(a11y): fix a11y warnings in various components

### PR DESCRIPTION
**Pull request by tw15egan**
Fixes the `a11y` warnings being thrown during the linting step. To avoid breaking changes, I've removed `jsx-a11y/no-static-element-interactions

#### Changelog

**New**

- Added `tabIndex`, `role` to select components

**Changed**

- `AccordionItem`
- `ComposedModal`
- `Dropdown`
- `DropdownItem`
- `InteriorLeftNav`
- `InteriorLeftNavItem`
- `Modal`
- `Slider`
- `Switch`
- `Tab`
- `Tabs`

**Removed**

- A bit of extra things from `Dropdown` story

#### Testing

Make sure none of the above components are broken

### CODE REVIEW

**Comment by joshblack** [comment]
@tw15egan are we safe removing that rule? Is this something that is coming up from the component stories? I know you mentioned that when we talked about this previously, was just curious. The rule itself seems valuable so was wondering why we wouldn't want it.

**Comment by tw15egan** [comment]
Just turned it off while I was working on it, but to get rid of a lot of those warning's we'd have to move a bunch of the onClick handlers to different elements. Not sure how this would affect end users. I can add the warning back in for now

**Comment by tw15egan** [comment]
Updated to `eslint-plugin-jsx-a11y` and fixed the new errors 😄

**Comment by marijohannessen** [comment]
👍 ✅

**Pull request merged**
