### PR TITLE
Added isExpanded prop in InteriorLeftNavList

### PR DESCRIPTION
**Pull request by ehdsouza**
For the InteriorLeftNav we need isExpanded behavior where we want the child lists to be kept opened unless closed by the user. Closing one child list shouldn't close the other opened lists.

fixes https://github.com/carbon-design-system/carbon-components-react/issues/328

Closes carbon-design-system/carbon-components-react#

#### Changelog

**New**

- Added props isExpanded in `InteriorLeftNavList`

### CODE REVIEW

**Comment by ehdsouza** [comment]
@marijohannessen thanks for the review comments. Renamed `isAccordion` to `isExpanded`.

**Comment by joshblack** [comment]
One question just to help catch me up, what's the motivation behind the `open` prop for the `NavList`?

**Comment by ehdsouza** [comment]
@joshblack there is no `open` prop. Its `isExpanded` prop for the `InteriorLeftNav` for our console [watson console](https://console.bluemix.net/developer/watson/dashboard). So, when one list is opened, we dont want any other opened lists to close.

Look at the [328](https://github.com/carbon-design-system/carbon-components-react/issues/328) for a detailed explanation

**Comment by joshblack** [comment]
Not sure if it was clear, but am talking about: `<InteriorLeftNavList className="second" open />`

**Comment by ehdsouza** [comment]
The test case checks the behavior when a user is expanding one list, any other opened lists behavior is unaffected. So it still stays as what it was ie `open` when `isExpanded` is set to true

**Comment by joshblack** [comment]
It's not really about the test case, regardless, what's the motivation behind having `isExpanded` on the container component versus on the child `NavList` components?

**Comment by ehdsouza** [comment]
@joshblack I got your point. I added the isExpanded to the child component `InteriorLeftNavList`. Let me know if any more suggestions

**Comment by germanattanasio** [comment]
when will this be release?

**Comment by tw15egan** [comment]
@germanattanasio  Should be included with the latest release

**Comment by joshblack** [comment]
@germanattanasio although it's not in the changelog,  it's included in the 4.2.2 tag: https://github.com/carbon-design-system/carbon-components-react/releases/tag/v4.2.2

**Pull request merged**
