### PR TITLE
fix(accordionItem): allow accordionItem to update on prop change

### PR DESCRIPTION
**Pull request by tw15egan**
### Accordion fix

Closes https://github.com/carbon-design-system/carbon-components-react/issues/61

### CODE REVIEW

**Comment by nicoxxie** [comment]
I think the code looks good, though seems like there is no test that covers this addition of prop change.  If someone else from the team think it's OK, please merge.

**Comment by hellobrian** [comment]
@tw15egan, on line 39 of AccordionItem-test.js, you can add another `expect` to test that the component is updating state via props:

```js
 it('can be open when open is true', () => {
  const openItem = shallow(
    <AccordionItem title="A heading" open>
      Lorem ipsum.
    </AccordionItem>
  );
  expect(openItem.hasClass('bx--accordion__item--active')).toEqual(true);
  expect(openItem.state().open).toEqual(true);
});
```

**Comment by tw15egan** [comment]
@hellobrian added!

**Comment by chrisdhanaraj** [comment]
👍 ✅  good by me as well

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170707-200832 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170707-200832") to [Bluemix Design System](https://console.bluemix.net/apps/1a30065f-cef2-4933-ba3f-3ff6669a0abd?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit 3cf593cfcb0572daab83f312a4fe3988b84a20b8

**Pull request merged**
