### PR TITLE
fix(DatePicker): show DatePicker when cliking in the icon in single with calendar

### LINKED ISSUE #800: Clicking on calendar icon in DatePicker does not bring up the DatePicker
####Description

If I hover over the calendar icon, the mouse cursor changes to indicate that it is clickable.  However, if I click on it, nothing happens.  Instead, clicking inside the edit box changes brings up the calendar popup.
I thought that there was maybe a problem with my implementation, but the behavior is the same in the storybook for the "single with calendar" variation.

I think that the calendar should only come up when you click on the icon and not when you click on the edit field.  Alternatively, the mouse cursor should not change when hovering over the calendar icon.

> What browser are you working in? **Chrome**

> What version of the Carbon Design System are you using?
		"carbon-components": "8.16.1",
		"carbon-components-react": "5.23.1",
		"carbon-icons": "6.3.1",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
OpenPages

## Steps to reproduce the issue
Try it in the story book for Date Picker - single with calendar

### PR DESCRIPTION
**Pull request by rezak-otmani**
Closes #800

Show DatePicker when cliking in the icon in single with calendar as was in Vanilla Carbon component

#### Changelog

**New**

**Changed**

* show `DatePicker` when cliking in the icon in `single with calendar`

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
cc @marijohannessen this is updating one of the tests, seems like the default behavior for this is not to render the icon? Just wanted to double-check 🙂

**Comment by asudoh** [comment]
Seems that the change creates duplicate `<svg>`s, one in `<DatePicker>` and another in `<DatePickerInput>`:

date-picker-icon

IIUC @marijohannessen’s original implementation - The single version embeds the icon in the input box whereas the range version puts the icon next to the 2nd input box.

@rezak-otmani do you want to try making a change to `<DatePickerInput>` instead of to `<DatePicker>`? Thanks!

**Comment by joshblack** [comment]
cc @marijohannessen to weigh in on the DatePicker stuff here

**Comment by marijohannessen** [comment]
I'm not sure I quite understand the question directed to me here - but I think everything looks good at least and it doesn't seem to have changed the actual component?

**Comment by asudoh** [comment]
Hi @marijohannessen here's my question - Is it correct that the single version embeds the icon in the input box whereas the range version puts the icon next to the 2nd input box? Thanks!

**Comment by marijohannessen** [comment]
Yes, that's correct!

**Comment by asudoh** [comment]
Thanks @marijohannessen for confirmation. @rezak-otmani let us know if you want to make this PR reflect such fact. Thanks!

**Comment by joshblack** [comment]
Closing this PR due to inactivity. Feel free to re-open if you want to address the feedback that @asudoh left!

**Pull request closed without merging**
