### PR TITLE
feat(css-prefix): removed hardcoded css-prefix

### PR DESCRIPTION
**Pull request by deblasis**
Closes carbon-design-system/carbon-components-react#2361

Replaced all the hardcoded instances of "bx--" with a prefix variable

#### Changelog

**New**

- added a settings.js to allow css-prefix override in storybook

**Changed**

- replaced `bx` instances with ${prefix} sourced from carbon-components (default is `bx`)

### CODE REVIEW

**Comment by asudoh** [comment]
Hi 👋 thank you for your contribution! Please be advised that this repository no longer hosts the latest code, please go https://github.com/carbon-design-system/carbon instead. Looking forward to seeing you there!

**Comment by deblasis** [comment]
Hi!

I can't say no to a monorepo! :) I'll refactor accordingly and PR there.

BTW I recommend updating the README
in carbon-design-system/carbon-components-react so that contributors are
aware of that.

Best

**Comment by joshblack** [comment]
Thanks @deblasis! Going to close this for now. Definitely agreed on updating the README! Will get to it 😄

**Comment by deblasis** [comment]
No problem @joshblack ! 👍  Anyways, I managed to open the same issue and refactor the code to work with the monorepo layout under carbon-design-system/carbon **before** the bot moved #2361, so there's a duplicate now:
- https://github.com/carbon-design-system/carbon/issues/2694
- https://github.com/carbon-design-system/carbon/issues/2689

Just for the records 😄 

cc @asudoh

**Pull request closed without merging**
