### PR TITLE
fix(overflow): wrap ref usage in if statement anyways

### PR DESCRIPTION
**Pull request by chrisdhanaraj**
Opening this to let people test against this, to see if this resolves the null issue. I haven't been able to isolate an appropriate test case to reproduce the bug though

### CODE REVIEW

**Comment by asudoh** [comment]
Yeah good to understand what the root cause is - Esp. the timing of component lifecycle vs the timing of `getMenuPosition()` being called.

**Comment by eddiemonge** [comment]
I'm in favor of this

**Comment by hellobrian** [comment]
I want to approve this but is this good to go? Were we looking for people to test this manually or something?

**Comment by chrisdhanaraj** [comment]
This is pretty much good to go

**Comment by hellobrian** [comment]
I'm merging this 👍 ✅

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console-regional.ng.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console-regional.ng.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170808-205936 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170808-205936") to [Bluemix Design System](https://console.bluemix.net/apps/eadc6714-41e7-421f-8313-02618b55185f?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit 5ba1d3f01f77b90afb873b5d1809d4ecda2ed53b

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532") to [Bluemix Design System](https://console.bluemix.net/apps/bc75a101-6472-481c-b48d-3eed1e9703f3?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit 0fa7dff96531de6ad25660e1d165f97d7ff3583c

**Pull request merged**
