### PR TITLE
fix(pageSize): add pageSize prop back in

### PR DESCRIPTION
**Pull request by chrisdhanaraj**
Resurrects this feature: https://github.ibm.com/Bluemix/bluemix-components-react/pull/537

### CODE REVIEW

**Comment by tw15egan** [comment]
👍 ✅ ❗️ 

After looking at this, I think we also made changes to allow for an unknown number of pages on the 2.x branch. Is that something we want to bring over as well?

**Comment by marijohannessen** [comment]
👍 ✅

**Comment by nicoxxie** [comment]
@tw15egan Yes that would be great to have

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170707-200832 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170707-200832") to [Bluemix Design System](https://console.bluemix.net/apps/1a30065f-cef2-4933-ba3f-3ff6669a0abd?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit 55d46f4ee52d4953cad18305f596974381163f86

**Pull request merged**
