### PR TITLE
fix(Dropdown): Update selectedTest when component receives new props

### PR DESCRIPTION
**Pull request by tonitagd**
Closes carbon-design-system/carbon-components-react#241 

Carbon Dropdown was not updating its selected value when the property `selectedTest` is passed.

#### Changelog

**Changed**

- Dropdown.js
- DropdownStory.js

### CODE REVIEW

**Comment by tonitagd** [comment]
@tw15egan can you take a look?

**Comment by marijohannessen** [comment]
Hey @tonitagd , can you resolve the conflicts in this PR?

**Comment by tonitagd** [comment]
@marijohannessen done

**Comment by tw15egan** [comment]
Looks good, thanks for fixing this!  👍 ✅

**Comment by tw15egan** [comment]
@tonitagd sorry, but looks like there is another merge conflict as we're processing our PR's

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171018-161759 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171018-161759") to [Bluemix Design System](https://console.bluemix.net/apps/1bd87b20-d62d-46c8-8783-4b67493838f1?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit 5659a8faa9e6bba6e49a3408cd47b20bb3e6edba

**Pull request merged**
