### PR TITLE
Fixes server-side rendering

### PR DESCRIPTION
**Pull request by germanattanasio**
* Added `window-or-global` to the `devDependencies`
* Use `import window from 'window-or-global` in every file that requires accessing the `window` object
* 🎨 Updated `CONTRIBUTING.md` with links to this repository instead of the GHE repo.

### CODE REVIEW

**Comment by chrisdhanaraj** [comment]
:+1:

**Comment by chrisdhanaraj** [comment]
Actually one thing - think `window-or-global` should be a dependency, not a devDep

**Comment by germanattanasio** [comment]
@chrisdhanaraj done

**Comment by chrisdhanaraj** [comment]
👍

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170707-200832 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170707-200832") to [Bluemix Design System](https://console.bluemix.net/apps/1a30065f-cef2-4933-ba3f-3ff6669a0abd?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit e8faa8c0be6da847c28e61013074bb70efe99aa2

**Pull request merged**
