### PR TITLE
feat(CodeSnippet): add wrappedContentRef to access <pre> contents

### PR DESCRIPTION
**Pull request by joshblack**
Closes carbon-design-system/carbon-components-react#55

Updates `CodeSnippet` to include a new prop, `wrappedContentRef`, that allows access to the `<pre>` element in the component (making it easier to copy!).

#### Changelog

**New**

**Changed**

- `CodeSnippet`
  - Added `wrappedContentRef` as a new prop
- `CodeSnippet-test`
  - Added test to assert ref is called and passes the correct node

**Removed**

### CODE REVIEW

**Comment by jzhang300** [comment]
I don't know how I feel about using `ref`, that's going away isn't it?

**Comment by joshblack** [comment]
They shouldn't be, unless I missed something substantial 😱 

Do you have a reference that says that @jzhang300 ?

**Comment by joshblack** [comment]
Just as a side-note for reviewers, this PR definitely doesn't have to be merged in. The requesting issue could 100% be solved a different way (I believe), especially since they have access to the content itself so setting up a click handler to pass that in should be trivial.

**Comment by tw15egan** [comment]
The old format of using ref as a string has been deprecated, but it looks like this supports the format of passing in a function e.g `ref={node => this.node = node}`

https://reactjs.org/docs/refs-and-the-dom.html

**Comment by tw15egan** [comment]
I'm good with this 👍 ✅

**Comment by marijohannessen** [comment]
Looks good to me too! 👍 ✅  Can you update your branch so it's up to date before merging?

**Pull request merged**
