### PR TITLE
fix(OverflowMenu): match experimental spec

### PR DESCRIPTION
**Pull request by emyarod**
Closes IBM/carbon-components-react#1985

This PR incorporates feedback from the March 2019 overflow menu component audit

Depends on

IBM/carbon-components#2053

IBM/carbon-components#2054

https://github.com/IBM/carbon-components/pull/2102

### CODE REVIEW

**Comment by asudoh** [comment]
Removing `blocked` label as IBM/carbon-components#2053 as well as IBM/carbon-components#2054 have been resolved.

**Comment by emyarod** [comment]
thanks @asudoh, this PR is now ready for review

**Comment by shixiedesign** [comment]
Reviewed on Chrome: 
- [ ] Default: icon should be next to type, like right side overflow (vanilla)
image
- [ ] Overflow with links: icon position wrong in Overflow with links 
image
- [ ] Overflow with links: icon doesn't disable 
image
- [ ] Custom trigger: wrong focus outline 
- [ ] Custom trigger: is missing option with icon
image

**Comment by emyarod** [comment]
I think all of the points have been addressed now @shixiedesign, with the disabled icon color change being addressed in https://github.com/IBM/carbon-components/pull/2102

**Review by joshblack — APPROVED** [review]

**Review by shixiedesign — APPROVED** [review]
Looks good! 🎉

**Comment by asudoh** [comment]
@emyarod Could you please fix the merge conflict? Thanks!

**Comment by emyarod** [comment]
dependencies upgraded and merge conflict is resolved now @asudoh

**Pull request merged**
