### PR TITLE
Add support for useTitleInItem (tooltip on hover)

### PR DESCRIPTION
**Pull request by hyungskim**
- MultiSelect.Filterable doesn’t support `useTitleInItem` (tooltip on hover) #2328
- https://github.com/carbon-design-system/carbon-components-react/issues/2328

### CODE REVIEW

**Comment by vpicone** [comment]
What about itemTitleText for parity with the titleText prop?

**Comment by asudoh** [comment]
@vpicone I may be missing something, but any reference on `itemTitleText`?

**Comment by vpicone** [comment]
I was offering it as a naming alternative that more closely aligns with the parent titleText. I’m on my phone, so if that name doesn’t make sense in this context that’s okay too!

**Comment by asudoh** [comment]
@vpicone OK the prop name is for the parity with `<MultiSelect>` and changing the name altogether is a breaking change. We can consider the name change in future.

**Comment by hyungskim** [comment]
Hi @asudoh, do you the published version of carbon-component-react that contains this fix?

**Comment by asudoh** [comment]
Hi 👋 @hyungskim we recently switched to monthly-ish release cycle. Stay tuned!

**Comment by hyungskim** [comment]
@asudoh Hi, do you know which version has my fix? Looks like our production env still doesn't have this fix.

**Comment by asudoh** [comment]
Hi 👋 @hyungskim if it's the case, this PR may have slipped from our monorepo move. Would you mind creating an PR at https://github.com/carbon-design-system/carbon/pulls? Thanks!

**Comment by hyungskim** [comment]
@asudoh Looks like my fix is in there for MultiSelect.Filterable by checking at this sample but not sure which published version this one uses.

Screen Shot 2019-06-25 at 8 17 43 AM

**Comment by emyarod** [comment]
@hyungskim looks like this was merged into v10.3.2 https://github.com/carbon-design-system/carbon/commit/33795afae9bd24babe3fc49de3102e29c0d69d60#diff-e8c89a1867f093cba993a4c0fd1eb37d

**Comment by hyungskim** [comment]
@emyarod @asudoh Hmm, that makes sense as our production currently uses carbon 9 (v6.xxx). It would take some time to migrate to carbon 10 (v.10.x).  Do you think I should create a PR for carbon 9 but not sure which branch I should use?

**Comment by emyarod** [comment]
@hyungskim yeah you can target https://github.com/carbon-design-system/carbon-components-react/tree/v6

**Comment by hyungskim** [comment]
@emyarod Do I need a permission to push my change?  I didn't have this issue using master but I'm having an issue right now with v6. 

Screen Shot 2019-06-25 at 1 59 04 PM

**Pull request merged**
