### PR TITLE
chore: add PR template

### PR DESCRIPTION
**Pull request by joshblack**
Adds a simple PR template that's been useful for various projects that I've worked on. The intent is to provide context for the issue a PR is trying to solve, a brief description of it, and then a high-level overview of the changes being submitted.

Feel free to close if it's not useful, just figured it'd be a worthwhile addition to help standardize submissions 😄

### CODE REVIEW

**Comment by joshblack** [comment]
cc @chrisdhanaraj

**Comment by chrisdhanaraj** [comment]
Heyo could you change this to a chore? This shouldn't trigger a new release

**Comment by chrisdhanaraj** [comment]
Fine by me otherwise though 👍

**Comment by joshblack** [comment]
Done @chrisdhanaraj

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532") to [Bluemix Design System](https://console.bluemix.net/apps/bc75a101-6472-481c-b48d-3eed1e9703f3?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit 052beeb68b7dd9db6219c8e8790ce72ab97df13b

**Pull request merged**
