### PR TITLE
Fixed flatpickr isomorphic error

### PR DESCRIPTION
**Pull request by codejamninja**
Fixed issue #868

Closes carbon-design-system/carbon-components-react#

Fixed flatpickr isomorphic error

#### Changelog

**Changed**

* Only import flatpickr when window exists

### CODE REVIEW

**Comment by joshblack** [comment]
Hi @codejamninja! 👋 Thanks for making this PR! Seems like the status check failed because of file formatting differences. Can you make sure to run `yarn format` in a new commit? There should be a git hook that is registered when you run `yarn install` as well, supposedly, which can help catch these kinds of things in the future 👍

**Comment by codejamninja** [comment]
I'm sorry, but happens when FlatPickr is loaded. I get the error even when I don't use FlatPickr.

**Comment by codejamninja** [comment]
Is there a way to conditionally determine if it is UMD?

**Comment by asudoh** [comment]
@codejamninja The problem is *not* with "UMD" as the matter of fact - The problem happens whenever the code is built with Rollup. Rollup CommonJS plugin may help, but it breaks the coherency in our codebase where all modules are written in ESM.

Some options I can rattle off are:

* File an issue against https://github.com/flatpickr/flatpickr
* Codemod to wrap the entire FlatPickr code in a function so the code can be lazily-evaluated
* Let the FlatPickr class ref passed along via `props` (Breaking change)

**Comment by marijohannessen** [comment]
What's the status here @codejamninja @asudoh ?

**Comment by codejamninja** [comment]
@marijohannessen @asudoh, I wrapped flatpickr in a separate module.

https://github.com/codejamninja/isomorphic-flatpickr
https://github.com/codejamninja/isomorphic-flatpickr/blob/master/src/index.js

**Comment by asudoh** [comment]
@codejamninja Thank you for your continued interest in this area - Would you have a chance to try latest Flatpickr?

**Comment by codejamninja** [comment]
isomorphic-flatpickr is using the latest

**Comment by codejamninja** [comment]
I think this pull request is not needed anymore.

Issue #868 was fixed by #880

**Pull request closed without merging**
