### PR TITLE
fix page size number overflow when it's 3 digits #732

### LINKED ISSUE #732: Paginator: page size number overflow when it's 3 digits
## Detailed description

screen shot 2018-03-20 at 1 51 02 pm

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?
bug

> Is this issue related to a specific component?
PaginatorV2

> What did you expect to happen? What happened instead? What would you like to see changed?
icon should flow to right

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
5.29.4

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Cloud

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

### PR DESCRIPTION
**Pull request by rezak-otmani**
Closes #732

#### Changelog

**New**

no overflow when it's 3 digits

**Changed**
**Removed**

* `inline` pros of select components

### CODE REVIEW

**Comment by joshblack** [comment]
Hi @rezak-otmani! 👋 Thanks so much for taking the time to make this PR 😄 

One thing that would be incredibly helpful is to fill out the PR template when creating each PR. This helps us know what to look for in the changes, including what could potentially be a major change.

In addition, would help to include a brief description of the changes right below the `Closes #` line that discusses the approach taken in the PR and how it fixes the corresponding issue.

Thanks again!

**Comment by asudoh** [comment]
Need devs who have more insights in this area - @carbon-design-system/ui Can we apply non-inline `<Select>` for pagination? Do we think applying `width:auto` there will be a safer fix? Thanks!

**Comment by rezak-otmani** [comment]
Hi @asudoh you're right, I think that the origin of the issue comes from this line  https://github.com/carbon-design-system/carbon-components/blob/master/src/components/pagination/_pagination.scss#L108  in  *carbon-components*
 the size must be increased to support the size of the number more than 2 digits

**Comment by asudoh** [comment]
Thanks @rezak-otmani for sharing your thought! Closing this given the fix should be applied to another repo.

@carbon-design-system/ui Do we really need https://github.com/carbon-design-system/carbon-components/blob/master/src/components/pagination/_pagination.scss#L113 line? Thanks!

**Pull request closed without merging**
