### PR TITLE
fix(date-picker-input): default pattern is faulty

### PR DESCRIPTION
**Pull request by psachs21**
The default pattern for the input should be a valid regexp.

I don't know if the intention was to be `\d{1,2}\d{1,2}\d{4}` or if it was to be separated by /s or not.

#### Changelog

**Changed**

* Default `pattern` prop on DatePickerInput is now a valid regexp

### CODE REVIEW

**Comment by psachs21** [comment]
@joshblack turns out the pretty print is what's breaking this after all. What prettier wants for the default is not the same as what we actually want. Not sure how to get around this, to be honest. A jsfiddle of the broken behaviour is here: https://jsfiddle.net/zr4xtjnn/7/. Note that the validation only occurs on firefox.

**Comment by psachs21** [comment]
I've added lint and prettier ignores so the default prop doesn't get formatted.

**Comment by asudoh** [comment]
@joshblack Do you know if the regular expression is something that goes to `new RegExp()`? If so, I'm thinking that we'll need escape for string in addition to escape for regular expression.

**Comment by joshblack** [comment]
So quick question @psachs21, can we pass the regex directly as a prop versus the string representation?

**Comment by psachs21** [comment]
@joshblack @asudoh not that I can see. I tried it here: https://jsfiddle.net/n5u2wwjg/14768/

**Comment by psachs21** [comment]
@asudoh I believe it's escaped properly, is there some other adjustment you wanted? Just need one more review.

**Comment by asudoh** [comment]
Hi @psachs21 thank you for asking - I'm thinking it should be: `'\\d{1,2}\\/\\d{1,2}\\/\\d{4}'`

**Pull request merged**
