### PR TITLE
chore(prettier): Update prettier dependency

### PR DESCRIPTION
**Pull request by joshblack**
Breaking out from #258 so that doesn't turn into a monster PR 😄 

Just a simple QOL PR to update prettier, adding in an ignore file and custom config for Prettier in `package.json`. Also runs a new `prettier` task for `yarn`/`npm` on the existing codebase.

#### Changelog

**New**

- `.prettierignore`

**Changed**

- `package.json`
  - Updated `prettier` dependency
  - Created a `prettier` script
  - Created `prettier` config
- Ran `prettier` on existing files

**Removed**

### CODE REVIEW

**Comment by asudoh** [comment]
^ BTW you may want to re-run the Travis - Errored state as of now.

**Comment by joshblack** [comment]
Thanks @asudoh! Will update the conflicts 😄

**Comment by chrisdhanaraj** [comment]
Hey Josh, could you actually move some of these configuration into https://github.com/carbon-design-system/carbon-eslint/tree/master/packages/eslint-config-carbon.

Want to try to abstract out our prettier/eslint usage so that any React addon library can use it

**Comment by joshblack** [comment]
@chrisdhanaraj yeah for sure!

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171013-151319 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171013-151319") to [Bluemix Design System](https://console.bluemix.net/apps/99b5f499-ff10-4966-b12d-3701210073d1?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit 0ef25e1fb43365081b0cfced5b04f650ea883399

**Pull request merged**
