### PR TITLE
fix(TextArea): add ref forwarding to TextArea

### PR DESCRIPTION
**Pull request by webadam1**
I've added ref forwarding to the TextArea component the same way it's done in the TextInput component.

### CODE REVIEW

**Comment by emyarod** [comment]
just one thing, would you mind setting the `displayName` to be `TextArea`? similar to our other components that are forwarding refs

**Comment by webadam1** [comment]
Added displayName 👍

**Comment by emyarod** [comment]
@webadam1 did you need this for `v6`? if so we can revert this and open the PR to `v6` branch instead

**Comment by webadam1** [comment]
@emyarod No, I only need this for v10 Carbon, so I think I don't need it in the v6 branch.

**Comment by emyarod** [comment]
@webadam1 gotcha we can revert it in this legacy repo and merge it into `v6` branch since v10 changes are all contained in `@carbon/react`

**Pull request merged**
