### PR TITLE
Feature - Close after submit ModalWrapper 

### PR DESCRIPTION
**Pull request by Flyingcirc-Danger**
#218

Added an extra prop to the ModalWrapper that gives the choice of closing after submitting. This should ideally be reimplemented with async functions in the future so that the `submit` function would only close after fully resolving`.

To close after submit, the `handleSubmit` function should return the boolean  `true` and the `closeAfterSubmit` prop should be `true`

### CODE REVIEW

**Comment by hellobrian** [comment]
Just merged your other PR, but looks like it may have caused a merge conflict. We can start reviewing this PR as soon as the conflict is resolved

**Comment by Flyingcirc-Danger** [comment]
My mistake, I didn't rebase. Conflicts resolved.

**Comment by joshblack** [comment]
Hi there! 👋 

If you're still interested in getting this merged into the project, could you add tests for the added behavior for `ModalWrapper`?

**Comment by marijohannessen** [comment]
@Flyingcirc-Danger

**Pull request closed without merging**
