### PR TITLE
feat(MultiSelect): adding custom comparator

### PR DESCRIPTION
**Pull request by GabrieleBarboni**
As per defect https://github.com/carbon-design-system/carbon/issues/4383 introducing custom comparator on MultiSelect component

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
LGTM basically, would you be able to make a similar change to the filterable version? Thanks @GabrieleBarboni!

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @GabrieleBarboni!

**Comment by GabrieleBarboni** [comment]
@asudoh Who else can be contacted to approve the PR?

**Review by emyarod — APPROVED** [review]
looks good to me

**Pull request merged**
