### PR TITLE
feat(modal): new composed modal

### LINKED ISSUE #139: Interactive Modal displays blank primary button
I created a Modal with the `secondaryButtonText` specified but not the `primaryButtonText`, like so:

```
<Modal
    modalHeading="Natural Language Classifier"
    modalLabel="PRICING PLANS"
    open={isServicePricingModalOpen}
    primaryButtonDisabled
    secondaryButtonText="Back"
    onRequestClose={goBack}
/>
```

The secondary button displays fine, but the primary button still shows with no text. If the `primaryButtonText` is not specified, I do expect it to not render at all.

screen shot 2017-07-26 at 12 46 14 pm

### PR DESCRIPTION
**Pull request by chrisdhanaraj**
This creates a set of wrapper containers for Modals, as opposed to the more prescriptive previous method. The new Modal can now be used such as so

```js
<ComposedModal open>
  <ModalHeader>
    <h1>Testing</h1>
  </ModalHeader>
  <ModalBody>
    <p>
      Please see story for more examples and demo of the
      functionality.
    </p>
  </ModalBody>
  <ModalFooter>
    <Button kind="secondary">Cancel</Button>
    <Button kind="primary">Save</Button>
  </ModalFooter>
</ComposedModal>
```

or

```js
<ComposedModal open>
  <ModalHeader label="Optional Label" title="Example" />
  <ModalBody>
    <p className="bx--modal-content__text">
      Please see ModalWrapper for more examples and demo of the
      functionality.
    </p>
  </ModalBody>
  <ModalFooter primaryButtonText="save" />
</ComposedModal>
```

See the story for more complete documentation

Closes #139

### CODE REVIEW

**Comment by asudoh** [comment]
Looks great overall 🙂 - One naïve question (just food for thoughts) - Are any of `<ModalHeader>`, `<ModalBody>` or `<ModalFooter>` mandatory in modal? If it’s the case - Would we possibly emit such mandatory children if they are not explicitly specified from the caller?

**Comment by joshblack** [comment]
@chrisdhanaraj do you want to try and get this merged in before you leave or should we just close this?

**Comment by sppatel** [comment]
I would like to see this get in.  @joshblack do you know what the PR requirements are to get the necessary approvals to move forward with this?

**Comment by joshblack** [comment]
@sppatel at this point it's @chrisdhanaraj just fixing the CI build and then can definitely merge in 😄

**Comment by sppatel** [comment]
awesome thank you.  we are looking forward to adopting this immediately

**Comment by joshblack** [comment]
Following up on this, just need to add tests for the implementation and then should be good to merge in 👍

**Comment by marijohannessen** [comment]
Carried over to https://github.com/carbon-design-system/carbon-components-react/pull/298

**Pull request closed without merging**
