### PR TITLE
Update testing harness and upgrade prettier

### PR DESCRIPTION
**Pull request by joshblack**
This PR is for handling updating the current Jest configuration and including updates for both `enzyme` and `prettier`, with support for snapshot testing through `enzyme-to-json` set as a serializer for Jest.

With the update to `enzyme`, approximately 30 test suites had to be updated because of their usage of older `enzyme` APIs. For example, consider the following example:

```js
it('should set defaultChecked as expected', () => {
    const wrapper = render({
      defaultChecked: true,
    });

    const input = wrapper.find('input');
    expect(input.props().defaultChecked).toEqual(true);
    wrapper.setProps({ defaultChecked: false });
    expect(input.props().defaultChecked).toEqual(false);
  });
```

In `enzyme@2.x`, the reference that `input` held would be the up-to-date version of the wrapper. However, with `enzyme@3`, the operations no longer happen in-memory and so we have to do the following variation of the above test:

```
  it('should set defaultChecked as expected', () => {
    const wrapper = render({
      defaultChecked: true,
    });

    const input = () => wrapper.find('input');
    expect(input().props().defaultChecked).toEqual(true);
    wrapper.setProps({ defaultChecked: false });
    expect(input().props().defaultChecked).toEqual(false);
  });
```

#### Changelog

**New**

- New `config` directory with a nested `jest` sub-directory with various file transformers

**Changed**

- `package.json`
  - now uses the `test` target as an alias to jest, all jest commands should be run off of that
  - Now includes a dedicated Jest config
  - Now includes a dedicated Prettier config
  - Scripts are now in alphabetical order
- `components`
  - Formatting updates
  - Test updates
- `CI`
  - Updated `.travis.yml` to account for the new `test` script

**Removed**

- `jest-setup.js` in favor of the `config` directory

### CODE REVIEW

**Comment by joshblack** [comment]
cc @chrisdhanaraj

**Comment by joshblack** [comment]
Leaving this open for now, but broke out parts of this into two separate PRs (#265, #267) that should get merged in before this. Leaving this up for discussion for tomorrow, October 10th 2017.

**Comment by marijohannessen** [comment]
Hey @joshblack , can you resolve the conflict in this PR? And running `npm run test` fails for me, but I'm guessing that's because of the two other PR's you were mentioning that needs to be merged in first.

**Comment by joshblack** [comment]
@marijohannessen this one I just left open for review. @chrisdhanaraj said he would bring it up but I don't think he did haha.

I opened up two smaller PRs that should go in first, and then I was going to break out the test-specific changes and merge those in 👍

**Comment by joshblack** [comment]
Will close this in the meantime so there's no confusion!

**Pull request closed without merging**
