### PR TITLE
User is now allowed to specify type the input box can hold

### PR DESCRIPTION
**Pull request by miramurali23**
Added a prop type to slider so user can specify input field type.

### CODE REVIEW

**Comment by tw15egan** [comment]
@miramurali23 could you resolve the merge conflicts?

**Comment by jlpadilla** [comment]
Looks good, thanks @miramurali23 !

**Comment by tw15egan** [comment]
Looks great, thanks @miramurali23!

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171018-161759 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171018-161759") to [Bluemix Design System](https://console.bluemix.net/apps/1bd87b20-d62d-46c8-8783-4b67493838f1?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit b4fd391f727df2f46638e805a082f2f292fe60d4

**Pull request merged**
